# Generated by Django 3.1.4 on 2020-12-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozilgiris', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derszamanlama',
            options={},
        ),
    ]
