# Generated by Django 3.1.4 on 2020-12-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zildata',
            table='ozildefault',
        ),
    ]
