# Generated by Django 3.1.4 on 2020-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0007_auto_20201206_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='zildata',
            name='xzilgun',
            field=models.SmallIntegerField(choices=[[0, 'Pazartesi'], [1, 'Salı']], default=0, verbose_name='Günü Seçin'),
        ),
        migrations.AlterField(
            model_name='zildata',
            name='zilgun',
            field=models.SlugField(default=0, unique=True, verbose_name='Tanımlanan Gün'),
        ),
    ]
