# Generated by Django 3.1.4 on 2020-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0008_auto_20201206_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zildata',
            name='xzilgun',
            field=models.SmallIntegerField(default=0, verbose_name='Günü Seçin'),
        ),
    ]
