# Generated by Django 3.1.4 on 2020-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0010_auto_20201206_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zildata',
            name='xzilgun',
            field=models.SmallIntegerField(choices=[['Pazartesi', 0], ['Salı', 1], [2, 'Çarşamba']], default=0, verbose_name='Günü Seçin'),
        ),
    ]
