# Generated by Django 3.1.4 on 2020-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0011_auto_20201206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zildata',
            name='xzilgun',
            field=models.SmallIntegerField(choices=[[0, 'Pazartesi'], [1, 'Salı'], [2, 'Çarşamba']], default=0, verbose_name='Günü Seçin'),
        ),
    ]
