# Generated by Django 3.1.4 on 2020-12-06 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0015_auto_20201206_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 41, 47, 145307))),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
