# Generated by Django 3.1.4 on 2020-12-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0016_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UretZil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 21, 41, 22, 81225)),
        ),
    ]
