# Generated by Django 3.1.4 on 2020-12-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozildata', '0017_auto_20201206_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='UretZil',
        ),
    ]
