# Generated by Django 3.1.4 on 2020-12-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DersZamanlama',
            fields=[
                ('gun_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('ilk1', models.TextField(default=None)),
                ('ogr1', models.TextField(default=None)),
                ('cik1', models.TextField(default=None)),
                ('ilk2', models.TextField(default=None)),
                ('ogr2', models.TextField(default=None)),
                ('cik2', models.TextField(default=None)),
                ('ilk3', models.TextField(default=None)),
                ('ogr3', models.TextField(default=None)),
                ('cik3', models.TextField(default=None)),
                ('ilk4', models.TextField(default=None)),
                ('ogr4', models.TextField(default=None)),
                ('cik4', models.TextField(default=None)),
                ('ilk5', models.TextField(default=None)),
                ('ogr5', models.TextField(default=None)),
                ('cik5', models.TextField(default=None)),
                ('ilk6', models.TextField(default=None)),
                ('ogr6', models.TextField(default=None)),
                ('cik6', models.TextField(default=None)),
                ('ilk7', models.TextField(default=None)),
                ('ogr7', models.TextField(default=None)),
                ('cik7', models.TextField(default=None)),
                ('ilk8', models.TextField(default=None)),
                ('ogr8', models.TextField(default=None)),
                ('cik8', models.TextField(default=None)),
                ('ilk9', models.TextField(default=None)),
                ('ogr9', models.TextField(default=None)),
                ('cik9', models.TextField(default=None)),
                ('ilk10', models.TextField(default=None)),
                ('ogr10', models.TextField(default=None)),
                ('cik10', models.TextField(default=None)),
                ('ilk11', models.TextField(default=None)),
                ('ogr11', models.TextField(default=None)),
                ('cik11', models.TextField(default=None)),
                ('ilk12', models.TextField(default=None)),
                ('ogr12', models.TextField(default=None)),
                ('cik12', models.TextField(default=None)),
                ('ilk13', models.TextField(default=None)),
                ('ogr13', models.TextField(default=None)),
                ('cik13', models.TextField(default=None)),
                ('ilk14', models.TextField(default=None)),
                ('ogr14', models.TextField(default=None)),
                ('cik14', models.TextField(default=None)),
                ('ilk15', models.TextField(default=None)),
                ('ogr15', models.TextField(default=None)),
                ('cik15', models.TextField(default=None)),
                ('ilk16', models.TextField(default=None)),
                ('ogr16', models.TextField(default=None)),
                ('cik16', models.TextField(default=None)),
                ('ilk17', models.TextField(default=None)),
                ('ogr17', models.TextField(default=None)),
                ('cik17', models.TextField(default=None)),
                ('ilk18', models.TextField(default=None)),
                ('ogr18', models.TextField(default=None)),
                ('cik18', models.TextField(default=None)),
                ('ilk19', models.TextField(default=None)),
                ('ogr19', models.TextField(default=None)),
                ('cik19', models.TextField(default=None)),
                ('ilk20', models.TextField(default=None)),
                ('ogr20', models.TextField(default=None)),
                ('cik20', models.TextField(default=None)),
            ],
            options={
                'db_table': 'saat',
            },
        ),
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zilaktif', models.SmallIntegerField(default=1, verbose_name='Aktif')),
                ('metin', models.TextField(verbose_name='Metin')),
                ('mp3yolu', models.TextField(verbose_name='Path')),
                ('guncellendi', models.SmallIntegerField(default=0, verbose_name='Güncel')),
            ],
            options={
                'db_table': 'cal_duyur',
            },
        ),
        migrations.CreateModel(
            name='ZilData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dersbaslangicsaati', models.TimeField(default='09:00', verbose_name='Derslerin Başlangıç Saati')),
                ('toplanmasuresi', models.TimeField(default='00:10', verbose_name='Toplanma Süresi')),
                ('ogretmenzilsuresi', models.TimeField(default='00:03', verbose_name='Öğretmen Ders Bildirim Zili')),
                ('derssayisi', models.SmallIntegerField(default=10, verbose_name='Günlük Ders Sayısı')),
                ('derssuresi', models.TimeField(default='00:40', verbose_name='Ders Süresi')),
                ('tenefussuresi', models.TimeField(default='00:10', verbose_name='Tenefüs Süresi')),
                ('oglenarasiders', models.SmallIntegerField(default=6, verbose_name='Öğlen Arası')),
                ('oglenarasisuresi', models.TimeField(default='00:45', verbose_name='Öğlen Arası Süresi')),
                ('zilgun', models.SlugField(default=0, verbose_name='Gün No')),
                ('xzilgun', models.SmallIntegerField(choices=[[0, 'Pazartesi'], [1, 'Salı'], [2, 'Çarşamba'], [3, 'Perşembe'], [4, 'Cuma'], [5, 'Cumartesi'], [6, 'Pazar']], default=0, unique=True, verbose_name='Tanımlanan Günü')),
                ('active', models.BooleanField(default=False, verbose_name='Aktif Pasif')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'db_table': 'zildefault',
            },
        ),
        migrations.CreateModel(
            name='ZilMelodi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('melodiad', models.TextField(verbose_name='Melodi Adı')),
                ('yol', models.TextField(verbose_name='Path')),
            ],
            options={
                'db_table': 'melodipath',
            },
        ),
    ]
