# Generated by Django 3.1.4 on 2020-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zilaktif', models.SmallIntegerField(default=1, verbose_name='Aktif')),
                ('metin', models.TextField(verbose_name='Metin')),
                ('mp3yolu', models.TextField(verbose_name='Path')),
                ('guncellendi', models.SmallIntegerField(default=0, verbose_name='Güncel')),
            ],
            options={
                'db_table': 'cal_duyur',
                'managed': True,
            },
        ),
    ]
