# Generated by Django 3.1.4 on 2020-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyurumetin', models.TextField(verbose_name='Metin')),
                ('duyurutarihi', models.TimeField(verbose_name='Saati')),
                ('duyurukayittarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('duyuruaktif', models.BooleanField(default=False, verbose_name='Aktif')),
                ('duyuruperiyod', models.PositiveSmallIntegerField(verbose_name='Tekrar Sayısı')),
            ],
            options={
                'db_table': 'duyurular',
                'managed': True,
            },
        ),
    ]
